name: simple_chat
description: "Simple Chat Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  # Images
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  # Freezed
  freezed_annotation: ^3.1.0

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Models & Serialization
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^16.2.4

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # Google Sign-In
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  google_sign_in_ios: ^6.2.1

  # Audio
  record: ^6.1.1
  just_audio: ^0.10.5

  # Utils
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.7.1
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3

  # Testing
  mockito: ^5.5.0

flutter:

  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
  
  # Localization
  generate: true
